
-  hosts: all
   become: true
   pre_tasks:

   - name: install updates for CentOS
     dnf:
       update_only: yes
       update_cache: yes
     when: ansible_distribution == "centos"

   - name: install updates for Ubuntu
     apt:
       upgrade: dist
       update_cache: yes
     when: ansible_distribution == "Ubuntu"

-  hosts: ubuntu
   become: true
   roles:
     -  ubuntu

-  hosts: centos
   become: true
   roles:
     - centos
